### ISSUE TITLE
サーバーとクライアントのすべき処理

### ISSUE THREAD

**Issue by kumataro4160** [TateIsuKanna/syokudou#7]
サーバーから帰ってくる文字列("多重利用です!!!!!"、"不正な学生証です．"など)はクライアント側で決めるべきです

**Comment by TateIsuKanna** [comment]
何も入力されなかった時の処理をサーバー側でするのには賛成です．

サーバーが返すべきなのはエラーコードで，エラーメッセージを返すべきでないという事ですか?
クライアント側の変更無しにメッセージを一括変更出来るのが良いと思っていたのだけど．

単にメッセージを表示するだけでなく，サーバーの応答によってクライアントの動作を変えたいという事ですか?
それなら，HTTP等の様にエラーコードとメッセージを両方返すというのがありますね．

**Comment by kumataro4160** [comment]
エラーメッセージは本質的にはGUIの一部なのでクライアント側で処理すべきだと思いました。
あと何も入力されなかった時の処理はどちらでもいいかと思い、上のコメントは編集しました。

**Comment by kumataro4160** [comment]
サーバーからエラーコードを受け取って、それをどう表現するかがGUIの役目だと思っています。

**Comment by TateIsuKanna** [comment]
上にも書きましたが，エラーコード(状態)によって動作を変えたいという事ですか?例えばエラーの時はメッセージを赤にして警告音を鳴らすとか．

**Comment by kumataro4160** [comment]
そうです。サーバーはエラーコードだけ送って、クライアントはそれに応じて動作を変えます。警告音も鳴らせたらいいですね。

**Comment by TateIsuKanna** [comment]
ステータスコードからメッセージを作る実装をするなら
- メッセージのリストを作っておいてステータスコードをインデックスとしてアクセスしたら分岐いらない
- ステータスコードは[enum](https://docs.python.jp/3/library/enum.html)にして分かりやすくした方がいい

**Comment by kumataro4160** [comment]
サーバーとクライアントを実際に起動させて、動作させるにはどうすればいいですか

**Comment by TateIsuKanna** [comment]
syokudou_client.pyの`.connect(`のIPアドレスを`localhost`にして起動
